### ISSUE TITLE
Extending plugin for debugging

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/pirate-parrot#11]
@selul just wanted to start off a conversation for enabling the debug option in the plugin. I'm jotting down some points that come to my head.

1. each plugin should register itself with the PP plugin 
2. this registration will help in filtering out logs relevant only to chosen plugins
3. the PP plugin will have a selection screen where the user can choose which plugins the log will be generated for
4. each plugin should log the message along with the type of message
5. each plugin's messages will be stored in a transient for X minutes only if its enabled in #3
6. PP plugin will have an option to export logs into a file (like RN)
7. PP plugin will have an option to show the logs on the console/screen (like RN but loaded through ajax)

**Comment by selul** [comment]
@contactashish13 let's get the things started. 

Please have in mind those things when building the mechanism. 

1) The logs will be registered into the plugins via do_action following this format: 
`do_action('themeisle_log_event', $message, $log_type, $plugin_name, __FILE__, __LINE__ ); `
2) In the pirate parrot you can hook to the previous action and log the data insite the transient, file or console,. 
3) The selection screen will be inside the current Themeisle pirate parrot page, and will be accesible only from that page.

**Comment by contactashish13** [comment]
@selul do you think this is required? My thought was that if someone has 5 of our plugins, each will start logging as soon as parrot is installed. Maybe we can prevent that with this and save the database some grief. 

> each plugin should register itself with the PP plugin

**Comment by selul** [comment]
@contactashish13 i dont understand your question? That's why i recommended to use the do_action call when logging the data. if the PP is not installed the do_action call will not do anything, if the PP is installed, we will have a function that will capture the data from the do_action and store the logs and display them.

let me know your thoughts.

**Comment by contactashish13** [comment]
@selul i'm not disputing the do_action call. Assume we are using that in every plugin to log an event. There are 5 plugins and therefore many do_action calls and all of them adding to their own transient in the database. Typically when a user installs PP it is for debugging a particular plugin only, not all. In that case the user should be able to say, ok I want to log calls only for the selected plugin. All the other plugins do_action will not result in a database entry.

**Comment by selul** [comment]
the PP will be the colector and the one that will store the data in the transient, we will not store them in each plugin. 

Can't we filter the logs for the plugin we are interested in the PP logs dashboard ? That's why we send the 3rd parameter which holds the plugin name. What do you think ?

**Comment by contactashish13** [comment]
@selul I know PP will be the collector but do you want someone's instance logging everything from all themeisle plugins despite the fact that they might have installed PP only for debugging one particular plugin? Please understand I'm merely trying to reduce the load on the db. I know we will use the plugin name to filter **after** insertion, I'm talking about filtering **before** deciding to insert into the database or not.

**Comment by selul** [comment]
Yes, but how do you think we can enable the store only for a particular plugin, without any intervention from the user  ?

**Comment by contactashish13** [comment]
Exactly. That is why there will be 2 selections. The first is when every plugin registers its interest to log. All these interested plugins will show up with a checkbox. The user will select the plugin they want to enable for logging. Only that plugin's messages will go into the db, others will be ignored. The next selection screen will be to choose the type of log like the one in RN. In case the user chooses 2 plugins to log (maybe visualizer and visualizer pro), they will get a drop down above the type of logs screen.

But the above point can be ignored completely if you feel the db will not be stressed. Every do_action will result in a db insert, which is where my concern lies.

**Comment by selul** [comment]
@contactashish13 i dont want any intervention from the user side, i just want they to use the plugin as they do now, by calling the parrot. 

What we can do is, in the dashboard for logging, we will have checkboxes for the plugins available to store logs, we can enable/disable them when debugging on the user site and also the type of the logs.

what do you think ?

**Comment by contactashish13** [comment]
@selul i was talking about the dashboard only. Someone from our side will go into the dashboard, right? That is the someone I was calling a user. The end user, the user of plugin will not know what to do anyways. This is for us. Isn't that the case?

**Comment by selul** [comment]
yep, i thought that you are thinking that the user who use our plugins will do this. we can call the user of the PP `we`  😄 
As we agreed upon this, let's tackle this.

**Comment by contactashish13** [comment]
just to confirm, the end user will do nothing. he will merely call parrot and leave it to us to figure out what to do. do you expect him to do more, maybe send the logs?

**Comment by selul** [comment]
nop, it's enough for now.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/pirate-parrot/pull/13

My changes make sure the logging section will be shown only when the parrot user is logged in. This is so that the admin user does not get confused and has only the call parrot button. If you don't want that functionality, you can continue to keep the constant MIMIC_PARROT_USER true

Every plugin needs to use this to register its intent
```
// maybe in the init
do_action( 'ti_log_register', 'Visualizer');
```

I'm not sure why the build is failing:

![image](https://user-images.githubusercontent.com/12953439/27897140-1163052c-623c-11e7-8be6-a1510095504e.png)

**Comment by selul** [comment]
@contactashish13 i have fixed the error but i'm not able to see any error page and i'm logged in with the parrot user. 

also i dont understand what this line is doing: 
```
if ( isset( $_POST['pp-allow-plugins'] ) && wp_verify_nonce( $_POST['nonce'], 'pp-allow' ) ) {
			set_transient( 'ti_log_allowed', isset( $_POST['allow_plugin'] ) ? $_POST['allow_plugin'] : array() );
		}
```

Can we rename the tracking action from ti to **themeisle_log_event**, like i first told you ?

**Comment by contactashish13** [comment]
@selul you will see something like this
![image](https://user-images.githubusercontent.com/12953439/27957895-0e17b75c-633e-11e7-853b-249935f00ffd.png)


but only if you have called
```
do_action( 'ti_log_register', '<plugin name>');
```
As agreed in our conversation earlier, this call will register the plugin as a potential logger. This is the first half of the form.

The second half of the form is where you can toggle between the log types and plugins that have been **allowed** to log.

The portion of code you have highlighted is for the first half of the form.

**Comment by contactashish13** [comment]
@selul actually, please call the action in the init method i.e.

```
add_action('init', function() {
    do_action('ti_log_register', 'Visualizer');
} );
```

**Comment by selul** [comment]
@contactashish13 i dont like this approach of registering plugins to log, we can use a filter in the pirate parrot which we can get to get the names of the plugins to log for, and the ones which we show in the checkboxes area. in the plugin to log, we can alter the array with the plugin slug. 

something like : 

**In pirate parrot**
```
$plugins_to_log = apply_filters('pirate_parrot_log', array();
```
**in visualizer for instance**
```
add_filter('pirate_parrot_log', function($plugins) {
    $plugins[] = 'visualizer';
    return $plugins;
} );
```

**Comment by selul** [comment]
@contactashish13 please make sure the naming of the filter stays the same.

**Comment by contactashish13** [comment]
@selul i dont understand the difference between what you are suggesting and what I've implemented. can you explain the advantage over my implementation so that I can understand rather than blindly implement?

> please make sure the naming of the filter stays the same.
do you mean the filter should be called pirate_parrot_log?

**Comment by selul** [comment]
you have implemented the plugin registering using an action hook. Actions are used more to run a set of routines specific to a moment in execution. 
Filters are more likely a way of altering variables, which is the scope of registering.

I dont say that your approach is not working, but i feel like the one using filters will be better and more wordpress specific. 

The log store is totally fine, i'm only saying about the one which you enable the logs for a specific plugin.

Regarding your 2nd questions, yes i'm talking about the name of the filter.

**Comment by contactashish13** [comment]
@selul makes sense. thanks! I'll change the implementation. BTW, the debugging mechanism helped in solving Keith's problem :)

**Comment by selul** [comment]
@contactashish13 great to hear that. i will merge the changes as soon as you have them ready.

**Comment by contactashish13** [comment]
@selul done
