### ISSUE TITLE
Fatal error with PHP 8.1

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/pirate-parrot#30]
Steps to replicate it:
1. create a WP instance with PHP 8.1
2. install & activate the plugin
3. call parrot in Dashboard -> Tools -> Themeisle Support Parrot
4. try deactivating the plugin

```
Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class TI_Parrot does not have a method "delete_account" in /s2-trickyfly/wordpress/wp-includes/class-wp-hook.php:307
Stack trace:
#0 /s2-trickyfly/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#1 /s2-trickyfly/wordpress/wp-includes/plugin.php(474): WP_Hook->do_action()
#2 /s2-trickyfly/wordpress/wp-admin/includes/plugin.php(812): do_action()
#3 /s2-trickyfly/wordpress/wp-admin/plugins.php(209): deactivate_plugins()
#4 {main}
  thrown in /s2-trickyfly/wordpress/wp-includes/class-wp-hook.php on line 307
```

Plugin version 1.4.0

**Comment by girishpanchal30** [comment]
Hello @stefan-cotitosu,

Can you please share your test WP instance details? because I'm not able to find out the v1.4.0 plugin and this issue does not happen with v1.3.0
Github release: https://github.com/Codeinwp/pirate-parrot/releases

Thanks

**Comment by stefan-cotitosu** [comment]
@girishpanchal30 sure, here it is.

 Admin area URL: https://shineowner.s3-tastewp.com/wp-admin 
 Username: stefancoti 
 Password: yZZRb0q1c1o

**Comment by girishpanchal30** [comment]
Hello @stefan-cotitosu,

I have checked with your WP test instance and a fatal error appears when deactivating the plugin.
Also, I have compare code in with github(master branch) and it totally diffrent with v1.4.0 plugin.
You can check here: https://www.diffchecker.com/VhMSeHON

Can you please share the 1.4.0 plugin GitHub repo/branch?

cc @selul
Thanks

**Comment by stefan-cotitosu** [comment]
@girishpanchal30 thank you for checking. I'm not sure where I got that version, 1.4.0, had it downloaded on my computer since 2021.

I've just tested with the same plugin version we provide to the customers, 1.3.0, and the issue doesn't occur anymore. I'm sorry for the confusion, closing this now.
